---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: mongodb
 namespace: default
 labels:
  app: mongodb
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mongodb
 template:
  metadata:
   labels:
    app: mongodb
  spec:
   containers:
   - name: mongo
     # 3.6.8 is the version, change if need
     image: mongo:3.6.8
     env:
     - name: MONGO_INITDB_ROOT_USERNAME
       valueFrom: 
        secretKeyRef:
         name: mongodb-cred
         key: MONGO_INITDB_ROOT_USERNAME
     - name: MONGO_INITDB_ROOT_PASSWORD
       valueFrom:
        secretKeyRef:
         name: mongodb-cred
         key: MONGO_INITDB_ROOT_PASSWORD
     - name: MONGO_INITDB_DATABASE
       # the database to which our credentials unlock
       value: admin
     ports:
     - containerPort: 27017
     resources: {}
     volumeMounts:
     - mountPath: /data/db
       name: mongodb-claim
   volumes:
   - name: mongodb-claim
     persistentVolumeClaim:
      # name of the volume claim which our pod will claim for itself
      claimName: mongodb-claim    
